server:
  port: 2001
spring:
  application:
    name: user
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 # 服务续约任务的调用间隔时间
    prefer-ip-address: true
    instance-id: user-service
  client:
    enabled: true # 启用Eureka客户端
    registry-fetch-interval-seconds: 30 # 注册表获取间隔时间
    register-with-eureka: true # 是否要将自身的实例信息注册到Eureka服务端
    fetch-registry: true # 是否从Eureka服务端获取注册信息
    service-url:
      defaultZone: http://172.17.0.2:8761/eureka/,http://172.17.0.3:8762/eureka/

store:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2 # 重新选择实例重试
    MaxAutoRetries: 1 # 使用选中的实例重试

feign:
  hystrix:
    enabled: false

# actuator 配置公开的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'