server:
  port: 2001
spring:
  application:
    name: user
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 # 服务续约任务的调用间隔时间
  client:
    enabled: true # 启用Eureka客户端
    registry-fetch-interval-seconds: 30 # 注册表获取间隔时间
    register-with-eureka: true # 是否要将自身的实例信息注册到Eureka服务端
    fetch-registry: true # 是否从Eureka服务端获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator 配置公开的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  eager-load:
    clients: