server:
  port: 3001
spring:
  application:
    name: store
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka/

# actuator ???????
management:
  endpoints:
    web:
      exposure:
        include: '*'
