server:
  port: 3001
spring:
  application:
    name: store
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: store-service
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://172.17.0.2:8761/eureka/,http://172.17.0.3:8762/eureka/

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
