server:
  port: 8762

spring:
  application:
    name: eureka

eureka:
  instance:
    instance-id: eureka
    prefer-ip-address: true
  client:
    enabled: true
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${peer1.hostname:127.0.0.1}:8761/eureka/