server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    instance-id: eureka
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${peer2.hostname:127.0.0.1}:8762/eureka/